name: simple_chat
description: "A simple chat application, supporting both desktop and web clients, developed using Flutter."
publish_to: none
homepage: https://github.com/yh4922/simple-chat
version: 0.0.5+5

# 

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_route: ^9.3.0+1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  flutter_localizations:
    sdk: flutter
  intl: any
  jh_debug: ^2.0.1
  shared_preferences: ^2.5.2
  window_manager: ^0.4.3
  url_launcher: ^6.3.1
  drift: ^2.25.1
  drift_flutter: ^0.2.4
  bot_toast: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  auto_route_generator: ^9.3.1
  riverpod_generator: ^2.6.4
  build_runner: ^2.4.15
  custom_lint: ^0.7.3
  riverpod_lint: ^2.6.4
  intl_utils: ^2.8.10
  flutter_launcher_icons: ^0.14.3
  drift_dev: ^2.25.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    # 图标字体
    - family: iconfont
      fonts:
        - asset: fonts/iconfont.ttf
    # 小米字体
    - family: MiSans
      fonts:
        - asset: fonts/MiSans-Regular.ttf
        - asset: fonts/MiSans-Bold.ttf
          weight: 700
        - asset: fonts/MiSans-Light.ttf
          weight: 300
        - asset: fonts/MiSans-Thin.ttf
          weight: 100

# 生成本地化代码 flutter pub run intl_utils:generate
flutter_intl:
  enabled: true
  arb_dir: lib/i18n/locale
  output_dir: lib/i18n/generated

# flutter 图标生成 dart run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_t.png"
  web:
    generate: true
    image_path: "assets/images/logo_t.png"
    background_color: "#F9E8EE"
    theme_color: "#F9E8EE"
    short_name: "Simple Chat"
  windows:
    generate: true
    image_path: "assets/images/logo_t.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo_t.png"